name: Deploy site to S3

on:
  workflow_run:
    workflows: ["Release"]   # must match name: in your release.yml
    types: [completed]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-site-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    # run only if the Release workflow succeeded, or if manually dispatched
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      # If triggered by workflow_run, check out the *same commit* that built the release
      - name: Checkout (same commit as Release)
        if: ${{ github.event_name == 'workflow_run' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # If triggered manually, just check out default branch HEAD
      - name: Checkout (default)
        if: ${{ github.event_name != 'workflow_run' }}
        uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION || 'ap-south-1' }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_UNSEEN }}

      # (optional) sanity: show which account/role is assumed
      - name: Who am I
        run: aws sts get-caller-identity

      - name: Upload site files
        run: |
          aws s3 cp site/index.html s3://${{ vars.S3_BUCKET_UNSEEN || 'unseenbrowser.hnetechnologies.com' }}/index.html \
            --content-type 'text/html; charset=utf-8' \
            --cache-control 'no-store, max-age=0, must-revalidate'
          aws s3 cp site/gtm.js s3://${{ vars.S3_BUCKET_UNSEEN || 'unseenbrowser.hnetechnologies.com' }}/gtm.js \
            --content-type 'application/javascript; charset=utf-8' \
            --cache-control 'public, max-age=86400'
          aws s3 cp site/company_logo.png s3://${{ vars.S3_BUCKET_UNSEEN || 'unseenbrowser.hnetechnologies.com' }}/company_logo.png \
            --content-type 'image/png' \
            --cache-control 'public, max-age=31536000, immutable'

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DIST_ID_UNSEEN }} \
            --paths "/index.html"
